
version: 2.1
commands:
   append_ips_to_inventory:
       description: "Gets AWS EC2 Instances IPS and append to inventory file"
       parameters:
         to:
            type: string
       steps:
           - run: aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:Project,Values=<<parameters.to>>" --output text >> inventory   
jobs:
  create_infra_ec2:
      docker: 
        - image: amazon/aws-cli
      steps:
         - checkout
         - run:
             name: Create Cloudformation Stack in AWS
             command: |
               aws cloudformation deploy \
               --template-file ec2-template.yml \
               --stack-name ec2-infra-${CIRCLE_WORKFLOW_ID:0:5} \
               --region us-east-1

  get-ec2-ips:
   docker:
      - image: circleci/node:13.8.0
   steps:
      - checkout
      - run:
          name: "Creates inventory file"
          command: touch inventory
      - run:
          name: "Adds header to file"
          command: echo '[servers]' > inventory
      - append_ips_to_inventory:
          to: 'udacity'
      - save_cache:
          paths:
            - "inventory"
          key: "ansible-inventory"

   print_ec2-ips:
    docker:
        - image: circleci/node:13.8.0
    steps:
        - checkout
        - restore_cache:
            key: "ansible-inventory"
        - run: cat inventory


workflows:
  ansible-circleci-infra:
    jobs:
      - create_infra_ec2
      - get-ec2-ips:
         requires:
           - "create_infra_ec2"
      - print_ec2-ips:
          requires:
            - "get-ec2-ips"