
version: 2.1
commands:
   append_ips_to_inventory:
       description: "Gets AWS EC2 Instances IPS and append to inventory file"
       parameters:
         to:
            type: string
       steps:
           - run: aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:Project,Values=<<parameters.to>>" --output text >> inventory  

   destroy_stack_rollback:
       description: "Detroy a Cloudformation Stack in case of fail to keep costs down"
       steps:
          - run: 
              name: Destroy Environment
              when: on_fail  
              command: |
                aws cloudformation delete-stack --stack-name ec2-infra-${CIRCLE_WORKFLOW_ID:0:5}
jobs:
  create_infra_ec2:
      docker: 
        - image: amazon/aws-cli
      steps:
         - checkout
         - run:
             name: Create Cloudformation Stack in AWS
             command: |
               aws cloudformation deploy \
               --template-file ec2-template.yml \
               --stack-name ec2-infra-${CIRCLE_WORKFLOW_ID:0:5} \
               --region us-east-1
  get-ec2-ips:
   docker:
      - image: amazon/aws-cli
   steps:
      - checkout
      - run:
          name: "Creates inventory file"
          command: touch inventory
      - run:
          name: "Adds header to file"
          command: echo '[servers]' > inventory
      - append_ips_to_inventory:
          to: 'udacity'
      - persist_to_workspace:
            root: ~/
            paths:
              - "inventory"
      - save_cache:
          paths:
            - "inventory"
          key: "ansible-inventory"

  print_ec2-ips:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - restore_cache:
           keys: 
              - "ansible-inventory"
       - run: cat inventory

  configure_infrastructure: 
    docker:
      - image: python:3.11-rc-alpine
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: 
            - "c2:0a:4e:f2:1c:03:83:5c:ca:1f:5f:75:3a:1e:20:c8"
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory main.yml 

  smoke_testing:
     docker:
        - image: amazon/aws-cli
     steps:
        - checkout
        - run:
           name: smoke Testing
           command: return 1
        - destroy_stack_rollback

workflows:
  ansible-circleci-infra:
    jobs:
      - create_infra_ec2
      #- get-ec2-ips:
      #   requires:
      #     - create_infra_ec2
      #- print_ec2-ips:
      #    requires:
      #      - get-ec2-ips
      # - configure_infrastructure
      - smoke_testing