- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: "Install NodeJS"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "Install NPM"
  become: true
  apt:
    name: ["npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Creates Dir for web app"
  become: true
  file:
    path: ~/web
    state: directory

- name: "Copy Index page to dir"
  become: true
  copy:
     src: index.js
     dest: ~/web/index.js
     backup: yes

- name: "Starts Web Server"
  shell: 
      "pm2 start ~/web/index.js -f"